log_path = "/x/SteamLibrary/steamapps/compatdata/230410/pfx/drive_c/users/steamuser/AppData/Local/Warframe/EE.log"
wanted_bounties = [
    "/Lotus/Types/Gameplay/Eidolon/Encounters/DynamicAssassinate",
    "/Lotus/Types/Gameplay/Eidolon/Encounters/DynamicHijack",
    "/Lotus/Types/Gameplay/Eidolon/Encounters/DynamicRescue",
    "/Lotus/Types/Gameplay/Eidolon/Encounters/HiddenResourceCaches",
    "/Lotus/Types/Gameplay/Eidolon/Encounters/DynamicCapture"
]
